### ISSUE TITLE
HdrHistogram throws ArrayIndexOutOfBoundsException when fetching the percentile value

### ISSUE THREAD

**Issue by keshavpeswani** [ExpediaDotCom/haystack-trends#170]
When an interval is supplied with only duration values greater than max permissible value of histogram, and the histrogram.getValueAtPercentile is called to fetch 95th percentile values, the histrogram throws the following exception 

`Encountered the following error during processing:" java.lang.ArrayIndexOutOfBoundsException: percentile value not found in range\n    at org.HdrHistogram.AbstractHistogram.getValueAtPercentile(AbstractHistogram.java:761)\n    at com.expedia.www.haystack.trends.aggregation.metrics.HistogramMetric.mapToMetricDataList(HistogramMetric.scala:50)\n  at com.expedia.www.haystack.trends.aggregation.WindowedMetric.$anonfun$getComputedMetricDataList$1(WindowedMetric.scala:99)\n   at scala.collection.immutable.List.flatMap(List.scala:335)\n    at com.expedia.www.haystack.trends.aggregation.WindowedMetric.getComputedMetricDataList(WindowedMetric.scala:96)\n  at com.expedia.www.haystack.trends.aggregation.TrendMetric.$anonfun$getComputedMetricPoints$1(TrendMetric.scala:87)\n   at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)\n at scala.collection.immutable.Map$Map4.foreach(Map.scala:210)\n at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)\n    at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)\n   at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)\n    at com.expedia.www.haystack.trends.aggregation.TrendMetric.getComputedMetricPoints(TrendMetric.scala:85)\n  at com.expedia.www.haystack.trends.kstream.processor.MetricAggProcessorSupplier$MetricAggProcessor.$anonfun$process$2(MetricAggProcessorSupplier.scala:111)\n   at com.expedia.www.haystack.trends.kstream.processor.MetricAggProcessorSupplier$MetricAggProcessor.$anonfun$process$2$adapted(MetricAggProcessorSupplier.scala:99)\n    at scala.Option.foreach(Option.scala:257)\n at com.expedia.www.haystack.trends.kstream.processor.MetricAggProcessorSupplier$MetricAggProcessor.process(MetricAggProcessorSupplier.scala:99)\n   at com.expedia.www.haystack.trends.kstream.processor.MetricAggProcessorSupplier$MetricAggProcessor.process(MetricAggProcessorSupplier.scala:72)\n   at org.apache.kafka.streams.processor.internals.ProcessorNode$1.run(ProcessorNode.java:46)\n    at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:208)\n  at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:124)\n at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:85)\n    at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:80)\n    at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:216)\n   at org.apache.kafka.streams.processor.internals.AssignedTasks.process(AssignedTasks.java:403)\n at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:317)\n at org.apache.kafka.streams.processor.internals.StreamThread.processAndMaybeCommit(StreamThread.java:942)\n at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:822)\n   at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:774)\n   at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:744)\n`

**Comment by keshavpeswani** [comment]
Closing the issue as #171 fixes it
